---
- name: Install PostgreSQL packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql
    - postgresql-common

- name: Install Python packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-psycopg2

- name: Install UFW
  apt:
    name: ufw
    state: present
    update_cache: yes

- name: Allow SSH traffic on port 22
  ufw:
    rule: allow
    port: '22'
    proto: 'tcp'

- name: Allow PostgreSQL traffic on port 5432
  ufw:
    rule: allow
    port: '5432'
    proto: 'tcp'

- name: Enable UFW
  ufw:
    state: enabled

- name: Check if postgres cluster directory existS
  command: pg_lsclusters

  register: existing_clusters

- name: Initialize Postgresql cluster
  command: pg_createcluster 15 main --start
  when: "'15' not in existing_clusters.stdout" 

- name: Start and enable services
  service:
    name: postgresql
    state: started
    enabled: yes

- name: restart postgres
  service:
    name: postgresql
    state: restarted
