---
- name: Install PostgreSQL packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql
    - postgresql-common

- name: Install Python packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-psycopg2

- name: Check if postgres cluster directory existS
  command: pg_lsclusters

  register: existing_clusters

- name: Initialize Postgresql cluster
  command: pg_createcluster 15 main --start
  when: "'15' not in existing_clusters.stdout" 

- name: Start and enable services
  service:
    name: postgresql
    state: started
    enabled: yes

- name: restart postgres
  service:
    name: postgresql
    state: restarted
