---
- name: Install Python dependencies
  become: yes
  apt: name={{ item }} state=latest force=yes
  with_items:
    - python3
    - python3-setuptools
    - python3-dev
    - build-essential
    - python3-pip





 
















        
