---
- name: Install Git
  apt:
    name: git
    state: present
    update_cache: yes

- name: Install UFW
  apt:
    name: ufw
    state: present
    update_cache: yes

- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Allow HTTP traffic
  ufw:
    rule: allow
    port: '80'
    proto: 'tcp'

- name: Allow HTTPS traffic
  ufw:
    rule: allow
    port: '443'
    proto: 'tcp'

- name: Allow OpenSSH traffic
  ufw:
    rule: allow
    port: '22'
    proto: 'tcp'

- name: Allow traffic on for api server
  ufw:
    rule: allow
    port: '3000'
    proto: 'tcp'

- name: Enable UFW
  ufw:
    state: enabled

- name: Remove existing directory
  file:
    path: /var/www/inventory-app2
    state: absent

- name: Clone the repository
  git:
    repo: https://github.com/jbiehl88/inventory-app2.git
    dest: /var/www/inventory-app2

- name: Create .env file
  copy:
    dest: /var/www/inventory-app2/.env
    content: |
      REACT_APP_DB_HOST={{ db_host }}
      REACT_APP_DB_USER={{ db_user }}
      REACT_APP_DB_PASS={{ db_password }}
      REACT_APP_DB_NAME={{ db_name }}
      REACT_APP_DB_PORT={{ db_port }}
      REACT_APP_API_SERVER={{ api_server }}

- name: Configure Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/inventory-app2 

- name: Enable Nginx site
  file:
    src: /etc/nginx/sites-available/inventory-app2
    dest: /etc/nginx/sites-enabled/inventory-app2
    state: link

- name: Disable the default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent


- name: Install Node.js and npm
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - nodejs
    - npm

- name: Install project dependencies
  command: npm install
  args:
    chdir: /var/www/inventory-app2





























                  








- name: Run npm build
  command: npm run build
  args:
    chdir: /var/www/inventory-app2

- name: Set correct permissions for the /var/www/inventory-app2
  file:
    path: /var/www/inventory-app2
    mode: '0755'
    recurse: yes

- name: Set permissions for .env file
  file:
    path: /var/www/inventory-app2/.env
    mode: '0600'

- name: Install pm2 globally
  npm:
    name: pm2
    global: yes
    state: present

- name: Restart server with pm2
  command: pm2 restart server
  register: pm2_restart_result
  ignore_errors: yes  # Ignore errors in case the server isn't running yet

- name: Start server with pm2 if not running
  command: pm2 start server.js --name server
  args:
    chdir: /var/www/inventory-app2
  when: pm2_restart_result is defined and pm2_restart_result.rc != 0 # Only run if the restart failed





- name: Restart Nginx
  service:
    name: nginx
    state: restarted
  notify:
    - Ensure Nginx is running

- name: Reload Nginx to apply changes
  command: nginx -s reload
